<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-KOTTQC5D" name="usersystem.autotest" tests="35" failures="2" timestamp="29 Jun 2016 04:01:11 GMT" time="11.224" errors="0">
  <testcase name="testDataSource" time="0.278" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRegisterFail" time="0.048" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRegisterFail" time="0.057" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRegisterFail" time="0.048" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRegisterFail" time="0.058" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRegisterFail" time="0.055" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRegisterFail" time="0.052" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testSourceSystem" time="0.046" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRegisterSuccess" time="1.569" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRegisterSuccess" time="1.317" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRegisterSuccess" time="1.329" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRegisterSuccess" time="1.381" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRegisterSuccess" time="1.223" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRegisterSuccess" time="1.251" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testRepeatRegisterData" time="0.3" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testDataSource" time="0.054" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginFail" time="0.048" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginFail" time="0.049" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginFail" time="0.051" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginFail" time="0.056" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginFail" time="0.048" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin">
    <failure type="java.lang.AssertionError" message="expected [01213] but found [01211]">
      <![CDATA[java.lang.AssertionError: expected [01213] but found [01211]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin.testLoginFail(TestLogin.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testLoginFail -->
  <testcase name="testLoginFail" time="0.044" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginFail" time="0.045" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginFail" time="0.045" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginFail" time="0.046" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin">
    <failure type="java.lang.AssertionError" message="expected [01213] but found [01211]">
      <![CDATA[java.lang.AssertionError: expected [01213] but found [01211]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin.testLoginFail(TestLogin.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testLoginFail -->
  <testcase name="testLoginFail" time="0.053" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginFail" time="0.05" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginFail" time="0.049" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginSuccess" time="0.118" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginSuccess" time="0.111" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginSuccess" time="0.11" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testLoginSuccess" time="0.109" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testGetTokenListFail" time="0.055" classname="cn.com.digiwin.justsharecloud.testCases.getTokenList.cases.TestGetTokenList"/>
  <testcase name="testGetTokenListFail" time="0.05" classname="cn.com.digiwin.justsharecloud.testCases.getTokenList.cases.TestGetTokenList"/>
  <testcase name="testGetTokenListSuccess" time="0.055" classname="cn.com.digiwin.justsharecloud.testCases.getTokenList.cases.TestGetTokenList"/>
</testsuite> <!-- usersystem.autotest -->
