<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-KOTTQC5D" name="xiaozhiyun.usersystem.autotest" tests="10" failures="5" timestamp="29 Jun 2016 02:58:36 GMT" time="0.64" errors="0">
  <testcase name="testDataSource" time="0.33" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister"/>
  <testcase name="testGetTokenListFail" time="0.33" classname="cn.com.digiwin.justsharecloud.testCases.getTokenList.cases.TestGetTokenList"/>
  <testcase name="testDataSource" time="0.33" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin"/>
  <testcase name="testGetTokenListFail" time="0.086" classname="cn.com.digiwin.justsharecloud.testCases.getTokenList.cases.TestGetTokenList"/>
  <testcase name="testRegisterFail" time="0.002" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testRegisterFail() didn&amp;apos;t finish within the time-out 600">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testRegisterFail() didn't finish within the time-out 600
]]>
    </failure>
  </testcase> <!-- testRegisterFail -->
  <testcase name="testLoginFail" time="0.002" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testLoginFail() didn&amp;apos;t finish within the time-out 600">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testLoginFail() didn't finish within the time-out 600
]]>
    </failure>
  </testcase> <!-- testLoginFail -->
  <testcase name="testLoginFail" time="0.002" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testLoginFail() didn&amp;apos;t finish within the time-out 600">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testLoginFail() didn't finish within the time-out 600
]]>
    </failure>
  </testcase> <!-- testLoginFail -->
  <testcase name="testLoginFail" time="0.002" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testLoginFail() didn&amp;apos;t finish within the time-out 600">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testLoginFail() didn't finish within the time-out 600
]]>
    </failure>
  </testcase> <!-- testLoginFail -->
  <testcase name="testRegisterFail" time="0.005" classname="cn.com.digiwin.justsharecloud.testCases.register.cases.TestRegister">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testRegisterFail() didn&amp;apos;t finish within the time-out 600">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testRegisterFail() didn't finish within the time-out 600
]]>
    </failure>
  </testcase> <!-- testRegisterFail -->
  <testcase name="testLoginFail" time="0.004" classname="cn.com.digiwin.justsharecloud.testCases.login.cases.TestLogin">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testLoginFail() didn&amp;apos;t finish within the time-out 600">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testLoginFail() didn't finish within the time-out 600
]]>
    </failure>
  </testcase> <!-- testLoginFail -->
</testsuite> <!-- xiaozhiyun.usersystem.autotest -->
